# Generated by Django 3.2.16 on 2023-07-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_game', '0002_auto_20230703_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='football_game.Player'),
        ),
        migrations.DeleteModel(
            name='PlayerTeam',
        ),
    ]
