# Generated by Django 3.2.16 on 2023-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_game', '0004_gamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='used_players',
            field=models.ManyToManyField(to='football_game.Player'),
        ),
    ]
