# Generated by Django 3.2.16 on 2023-07-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_game', '0005_gamer_used_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='used_players',
        ),
        migrations.AddField(
            model_name='gamer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
